/**
 * 风格注册表
 * 前 8 套严格对应《设计方案.md》的方案一 ~ 方案八；后 3 套为本次新增。
 * tone 用于外壳判断该风格明暗（画廊里的标题字号、缩略图比例等）。
 */

export const STYLES = [
  {
    key: 'noir-ink',
    idx: '01',
    name: '墨石 · 暗夜墨黑',
    note: '中性黑白灰 / 衬线 / 静默不移位',
    source: '方案一',
    tone: 'dark',
    swatch: { bg: '#0d0d0d', accent: '#e5e5e5' },
    notes: '无纯白、无暖黄、灰轴 R=G=B；1px 墨线 + 哑光颗粒',
  },
  {
    key: 'linear',
    idx: '02',
    name: 'Linear 极简',
    note: '近黑 / Inter / 靛紫渐变 CTA',
    source: '方案二',
    tone: 'dark',
    swatch: { bg: '#0a0a0b', accent: '#5e6ad2' },
    notes: '无阴影、圆角 ≤ lg、仅透明度过渡',
  },
  {
    key: 'soft-ui',
    idx: '03',
    name: '柔雾靛 · 柔和界面',
    note: '浅色 / rounded-3xl / 彩色柔影',
    source: '方案三',
    tone: 'light',
    swatch: { bg: '#f8fafc', accent: '#4f46e5' },
    notes: '低饱和靛紫、hover 上浮、柔和彩色阴影',
  },
  {
    key: 'modern-gradient',
    idx: '04',
    name: '现代渐变',
    note: '玻璃卡片 / 渐变文字 / 光晕',
    source: '方案四',
    tone: 'dark',
    swatch: { bg: '#0b0620', accent: '#d946ef' },
    notes: '紫→品红渐变、blur-xl 玻璃、彩色阴影扩散',
  },
  {
    key: 'macos-vibrancy',
    idx: '05',
    name: 'macOS 毛玻璃',
    note: '三级深灰 / 1px 边框 / 无渐变',
    source: '方案五',
    tone: 'dark',
    swatch: { bg: '#1c1c1e', accent: '#0a84ff' },
    notes: '衬线标题 + 无衬线正文，层级靠灰阶不靠阴影',
  },
  {
    key: 'magic-circle',
    idx: '06',
    name: '魔法阵',
    note: '深海军蓝 / 金色辉光 / 同心圆环',
    source: '方案六',
    tone: 'dark',
    swatch: { bg: '#0a0920', accent: '#fbbf24' },
    notes: '法阵旋转、能量内爆、符文虚线边框',
  },
  {
    key: 'liquid-glass',
    idx: '07',
    name: 'Apple 流动玻璃',
    note: '彩虹折射边框 / 霓虹描边标题',
    source: '方案七',
    tone: 'dark',
    swatch: { bg: '#16213e', accent: '#ff2d92' },
    notes: '40px 模糊 + 1.8 饱和、渐变 + 3D 阴影文字',
  },
  {
    key: 'glassmorphism',
    idx: '08',
    name: '夜航玻璃拟态',
    note: '无色玻璃 / 香槟金 / 方向性阴影',
    source: '方案八',
    tone: 'dark',
    swatch: { bg: '#0b1322', accent: '#e4b863' },
    notes: '深墨夜景 + 柔和光斑、颗粒噪点、扫光高光',
  },
  {
    key: 'teal-mist',
    idx: '09',
    name: '松石青 · 晨雾',
    note: '新增｜冷青 / 通透留白 / 发丝线',
    source: '本次新增',
    tone: 'light',
    add: true,
    swatch: { bg: '#eff6f6', accent: '#0d9488' },
    notes: '松石青单色体系，低对比大留白，细发丝分隔',
  },
  {
    key: 'terracotta',
    idx: '10',
    name: '赤陶暖沙',
    note: '新增｜陶土赭石 / 手作颗粒',
    source: '本次新增',
    tone: 'light',
    add: true,
    swatch: { bg: '#faf4ec', accent: '#c2410c' },
    notes: '有机圆角、赭红强调、纸张噪点纹理',
  },
  {
    key: 'neo-brutalism',
    idx: '11',
    name: '新粗野主义',
    note: '新增｜3px 硬边 / 位移硬影',
    source: '本次新增',
    tone: 'light',
    add: true,
    swatch: { bg: '#f4f0e6', accent: '#111111' },
    notes: '零圆角、硬位移阴影、hover 抬起加厚',
  },
]

export const STYLE_MAP = Object.fromEntries(STYLES.map((s) => [s.key, s]))
export const STYLE_KEYS = STYLES.map((s) => s.key)
